export const TOGGLE_LOGIN = 'TOGGLE_LOGIN'
export const CHANGE_FIELDS_LOGIN = 'CHANGE_FIELDS_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'


export const TOGGLE_REG = 'TOGGLE_REG'
export const CHANGE_FIELDS_REG = 'CHANGE_FIELDS_REG'
export const RECEIVE_REG = 'RECEIVE_REG'
export const SUCCESS_REG = 'SUCCESS_REG'
export const FAILURE_REG = 'FAILURE_REG'